Add title to webpage when editing texture
pkp/texture pull request #87
Opened 2020-09-23 17:43 UTC by withanage

@NateWr
pkp/texture#85

2020-09-24 09:44 UTC, NateWr requested changes
Great! Just a few minor changes.

2020-09-24 09:44 UTC, NateWr commented on TextureHandler.inc.php
> +		$submission = $submissionDao->getById($submissionId);
Use `$this->getAuthorizedContextObject(ASSOC_TYPE_SUBMISSION)` here to avoid an additional database hit.

2020-09-24 09:44 UTC, NateWr commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
Use `$publication->getLocalizedData('title')` here. It should use the publication's locale.

And `Texture` will need to go into a translateable string in the plugin's `.po` file. It probably already exists as the plugin's name.

I've never seen `?:` before. How is it different from `??`?

2020-09-24 09:44 UTC, NateWr commented on templates/editor.tpl
> +		<title>{$title}</title>
Use `{$title|escape}` to prevent `<` and `>` in the title from causing problems.

2020-09-24 18:08 UTC, withanage commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
Actually should be the same as null coalescing  operator as [here](https://stackoverflow.com/questions/1506527/how-do-i-use-the-ternary-operator-in-php-as-a-shorthand-for-if-else) . Therefore set it as ??   as it is more used.

2020-09-24 18:09 UTC, withanage commented on TextureHandler.inc.php
> +		$submission = $submissionDao->getById($submissionId);
Thanks for   the tip. Changed!

2020-09-24 18:09 UTC, withanage commented on templates/editor.tpl
> +		<title>{$title}</title>
Changed!

2020-09-28 09:47 UTC, NateWr commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
Ah good to know, thanks! Fine either way, just happy to learn about it. :)

2020-09-28 09:49 UTC, NateWr commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
This part still needs to be done:

> And Texture will need to go into a translateable string in the plugin's .po file. It probably already exists as the plugin's name.

2020-09-28 10:37 UTC, withanage commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
Sorry Nate, totally missed that part, have chaned  in the latest commit 3ad503888be8860a0a16c070951c40466b233209

2020-09-28 10:44 UTC, NateWr commented on TextureHandler.inc.php
> +		$title = $publication->getData('title', $publication->getData('locale')) ?: 'Texture';
No apology necessary!

2020-09-28 10:45 UTC, NateWr approved these changes

2020-09-28 10:45 UTC, NateWr commented
Do you have permission to merge? If so, I'll leave the merge to you when you're ready.

2020-09-28 14:01 UTC, withanage commented
Thanks for the review Nate again. I learned lots of new stuff from the comments. Yes, I've got the permissions and will merge it, as soon as I've got the other js stuff also together, so I can release the plugin.

2020-10-11 10:43 UTC, merged